### ISSUE TITLE
Hi. I get the same error message when I try to run the dotplot or heatmap functions. As a consequence, I can't find the plot neither in the output directory nor anywhere else. Even though the plot pops up briefly...

### ISSUE THREAD

**Issue by RunningCrystal** [Teichlab/cellphonedb#211] opened 2020-10-25 06:47 UTC
Hi. I get the same error message when I try to run the dotplot or heatmap functions. As a consequence, I can't find the plot neither in the output directory nor anywhere else. Even though the plot pops up briefly... 
Any help?

`cellphonedb plot dot_plot
The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.`

_Originally posted by @hartmannmark in https://github.com/Teichlab/cellphonedb/issues/159#issuecomment-691101393_

**Comment by rgranit** [comment] 2020-10-26 13:39
Same here..

**Comment by prete** [comment] 2020-12-07 19:04
Duplicate of #159

**Closed by prete** 2020-12-07 19:04 UTC
