### ISSUE TITLE
error : ValueError: Columns must be same length as key

### ISSUE THREAD

**Issue by jinyuanchun** [Teichlab/cellphonedb#373] opened 2022-05-17 12:20 UTC
i use statistical_analysis method 
cmd : cellphonedb method statistical_analysis  Chondrocyte-Erythrocyte.0.meta.tsv Chondrocyte-Erythrocyte.0.matrix.tsv --counts-data=gene_name --output-path=out1
inport data 
Chondrocyte-Erythrocyte.0.meta.tsv
![image](https://user-images.githubusercontent.com/40689145/168808532-9811c029-adf6-477b-b5e6-baa62ee099b7.png)
Chondrocyte-Erythrocyte.0.matrix.tsv

but the error 
![image](https://user-images.githubusercontent.com/40689145/168809428-3defb315-06df-4a52-8d2c-eb3d76df6888.png)

**Comment by jinyuanchun** [comment] 2022-05-17 12:21
supplement
![image](https://user-images.githubusercontent.com/40689145/168809564-d6f69492-1e5c-43ca-b6d7-596781f40f94.png)

**Comment by colin-leeyc** [comment] 2022-06-01 08:20
Same issue! Uninstalled and re-installed cellphonedb, and it worked..

**Comment by ShiweiHePH** [comment] 2022-06-02 14:15
> 
That's true, I also address this issue via uninstalled and re-installed.

**Comment by ShiweiHePH** [comment] 2022-06-02 14:16
> 

https://github.com/Teichlab/cellphonedb/issues/373#issuecomment-1143273155

**Comment by ShiweiHePH** [comment] 2022-06-02 14:17
> Same issue! Uninstalled and re-installed cellphonedb, and it worked..

That's true, I also address this issue via uninstalled and re-installed.

**Comment by jinyuanchun** [comment] 2022-06-14 01:18
me too, re-install is ok

**Comment by prete** [comment] 2022-06-24 11:15
Hi @jinyuanchun glad to hear it's sorted. This is probably caused by a dependency issue. Something else may have been installed in the same environment and you possibly got a different version of pandas than the one required by CellPhoneDB. 

Closing this issue now as re-installing seems to be the way of fixing this.

**Closed as completed by prete** 2022-06-24 11:15 UTC

**Comment by jinyuanchun** [comment] 2022-10-11 07:24
thank you



---- Replied Message ----
| From | Shiwei ***@***.***> |
| Date | 06/02/2022 22:17 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [Teichlab/cellphonedb] error : ValueError: Columns must be same length as key (Issue #373) |

Same issue! Uninstalled and re-installed cellphonedb, and it worked..

That's true, I also address this issue via uninstalled and re-installed.
