### ISSUE TITLE
Installation issues Windows 10 Python 3.7

### ISSUE THREAD

**Issue by tgtan** [Teichlab/cellphonedb#249] opened 2021-01-08 09:43 UTC
Hi I'm using Python 3.7.3 and encountered the following error message when installing cellphonedb:
 ERROR: Command errored out with exit status 1:
     command: 'c:\users\tantzeg\cpdb-venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tantzeg\\AppData\\Local\\Temp\\pip-install-8g5c5r0h\\rpy2_2d9402f45ed84413b6850d962a2aaedb\\setup.py'"'"'; __file__='"'"'C:\\Users\\tantzeg\\AppData\\Local\\Temp\\pip-install-8g5c5r0h\\rpy2_2d9402f45ed84413b6850d962a2aaedb\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\tantzeg\AppData\Local\Temp\pip-pip-egg-info-l0dxeh0q'
         cwd: C:\Users\tantzeg\AppData\Local\Temp\pip-install-8g5c5r0h\rpy2_2d9402f45ed84413b6850d962a2aaedb\
    Complete output (91 lines):
    c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\cparser.py:165: UserWarning: Global variable 'R_NaN' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\cparser.py:165: UserWarning: Global variable 'R_NaReal' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\cparser.py:165: UserWarning: Global variable 'R_NaInt' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\cparser.py:165: UserWarning: Global variable 'R_NaString' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\cparser.py:165: UserWarning: Global variable 'R_BlankString' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\cparser.py:165: UserWarning: Global variable 'R_BlankScalarString' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\cparser.py:165: UserWarning: Global variable 'R_GlobalEnv' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\cparser.py:165: UserWarning: Global variable 'R_EmptyEnv' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\cparser.py:165: UserWarning: Global variable 'R_BaseEnv' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\cparser.py:165: UserWarning: Global variable 'R_BaseNamespace' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\cparser.py:165: UserWarning: Global variable 'R_BaseNamespaceRegistry' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\cparser.py:165: UserWarning: Global variable 'R_NilValue' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\cparser.py:165: UserWarning: Global variable 'R_UnboundValue' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\cparser.py:165: UserWarning: Global variable 'R_MissingArg' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\cparser.py:165: UserWarning: Global variable 'R_ClassSymbol' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\cparser.py:165: UserWarning: Global variable 'R_NameSymbol' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\cparser.py:165: UserWarning: Global variable 'R_DimSymbol' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
      "(usually 'extern')" % (decl.name,))
    Traceback (most recent call last):
      File "c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\cparser.py", line 336, in _parse
        ast = _get_parser().parse(fullcsource)
      File "c:\users\tantzeg\cpdb-venv\lib\site-packages\pycparser\c_parser.py", line 152, in parse
        debug=debuglevel)
      File "c:\users\tantzeg\cpdb-venv\lib\site-packages\pycparser\ply\yacc.py", line 331, in parse
        return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
      File "c:\users\tantzeg\cpdb-venv\lib\site-packages\pycparser\ply\yacc.py", line 1199, in parseopt_notrack
        tok = call_errorfunc(self.errorfunc, errtoken, self)
      File "c:\users\tantzeg\cpdb-venv\lib\site-packages\pycparser\ply\yacc.py", line 193, in call_errorfunc
        r = errorfunc(token)
      File "c:\users\tantzeg\cpdb-venv\lib\site-packages\pycparser\c_parser.py", line 1861, in p_error
        column=self.clex.find_tok_column(p)))
      File "c:\users\tantzeg\cpdb-venv\lib\site-packages\pycparser\plyparser.py", line 67, in _parse_error
        raise ParseError("%s: %s" % (coord, msg))
    pycparser.plyparser.ParseError: <cdef source string>:23:5: before: blah1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\tantzeg\AppData\Local\Temp\pip-install-8g5c5r0h\rpy2_2d9402f45ed84413b6850d962a2aaedb\setup.py", line 184, in <module>
        'rpy2': ['doc/source/rpy2_logo.png', ]}
      File "c:\users\tantzeg\cpdb-venv\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Program Files\Python37\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\users\tantzeg\cpdb-venv\lib\site-packages\setuptools\dist.py", line 424, in __init__
        k: v for k, v in attrs.items()
      File "C:\Program Files\Python37\lib\distutils\dist.py", line 292, in __init__
        self.finalize_options()
      File "c:\users\tantzeg\cpdb-venv\lib\site-packages\setuptools\dist.py", line 695, in finalize_options
        ep(self)
      File "c:\users\tantzeg\cpdb-venv\lib\site-packages\setuptools\dist.py", line 702, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "rpy/_rinterface_cffi_build.py", line 546, in <module>
        """ if os.name == 'nt' else ''
      File "c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\api.py", line 112, in cdef
        self._cdef(csource, override=override, packed=packed, pack=pack)
      File "c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\api.py", line 126, in _cdef
        self._parser.parse(csource, override=override, **options)
      File "c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\cparser.py", line 389, in parse
        self._internal_parse(csource)
      File "c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\cparser.py", line 394, in _internal_parse
        ast, macros, csource = self._parse(csource)
      File "c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\cparser.py", line 338, in _parse
        self.convert_pycparser_error(e, csource)
      File "c:\users\tantzeg\cpdb-venv\lib\site-packages\cffi\cparser.py", line 367, in convert_pycparser_error
        raise CDefError(msg)
    cffi.CDefError: cannot parse "blah1 ReadConsole;"
    <cdef source string>:23:5: before: blah1
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Appreciate any help with this! Thanks!

**Comment by prete** [comment] 2021-03-15 20:08
Duplicate of #245

**Closed by prete** 2021-03-15 20:08 UTC
